name: Slabs
main: chibill.slabs.Main
version: 2.2.0

commands:
  slab:
    description: Give the player a special slab that places upside down half-slabs.
    usage: /<command>
    permission: Slabs.slab
    permission-message: You don't have permission!
  slab-version:
    description: Reports the version of Slabs installed.
    usage: /<command>
    permission: Slabs.version
    permission-message: You don't have permission!